version: '2'
services:
  monitorrent:
     container_name: monitorrent
     hostname: monitorrent
     build: ./monitorrent
     ports:
       - 6687:6687/tcp
     volumes:
       - /opt/mediacenter/monitorrent-db:/db
     environment:
       - MONITORRENT_DB_PATH=/db/monitorrent.db
     links:
       - transmission

  transmission:
      container_name: transmission
      hostname: transmission
      build: ./transmission
      ports:
        - 9091:9091/tcp
        - 51413:51413/tcp
        - 51413:51413/udp
      volumes:
        - /opt/mediacenter/transmission-config:/config
        - /data/Media/Downloads:/downloads
        - /data/Media/Torrents:/watch
      environment:
        - PGID=1000
        - PUID=1000
      links:
        - filebot

  plex:
      container_name: plex
      hostname: plex
      build: ./plex
      restart: unless-stopped
      ports:
        - 32400:32400/tcp
        - 33400:33400/tcp
        - 3005:3005/tcp
        - 8324:8324/tcp
        - 32469:32469/tcp
        - 1900:1900/udp
        - 32410:32410/udp
        - 32412:32412/udp
        - 32413:32413/udp
        - 32414:32414/udp
      environment:
        - ADVERTISE_IP=http://127.0.0.1:32400/
        - PLEX_UID=1000
        - PLEX_GID=1000
      volumes:
        - /opt/mediacenter/plex-config:/config
        - /opt/mediacenter/plex-transcode:/transcode
        - /data/Media:/Media

  filebot:
      build: ./filebot
      container_name: filebot
      volumes:
          - /data/Media:/data/Media:rw
          - /data/Media/Downloads/complete:/data/Media/Downloads/complete:rw
          - /opt/mediacenter/filebot-config:/config:rw
          - /etc/localtime:/etc/localtime
      ports:
          - 8001:8001/tcp
